### ISSUE TITLE
point stack / build plan at patched version of argon2 

### ISSUE THREAD

**Issue by cartazio** [jpmorganchase/constellation#1]
[argon2-1.3.0.tar.gz](https://github.com/jpmorganchase/constellation/files/590600/argon2-1.3.0.tar.gz) is the patched one we're using for the release builds, but the current build directions / scripting doesn't reflect this yet

uploading a copy of it here so we can point builds to it. or something. 

or https://github.com/ocharles/argon2/pull/11 gets merged in and we dont need to :)

**Comment by patrickmn** [comment]
https://github.com/jpmorganchase/constellation/pull/8
