### ISSUE TITLE
Constellation Node config

### ISSUE THREAD

**Issue by jaguarg** [jpmorganchase/constellation#10]
Hi, 

I am doing a setup from scratch based on the 7-nodes example. I don't understand what is the relationship between a geth node and constellation node and where it is defined.

I can't see where it is defined that a given constellation node is "bound" to a given geth node. 

That's a constellation node config:
```
url = "http://127.0.0.1:9000/"
port = 9000
socketPath = "qdata/tm1.ipc"
otherNodeUrls = []
publicKeyPath = "keys/tm1.pub"
privateKeyPath = "keys/tm1.key"
archivalPublicKeyPath = "keys/tm1a.pub"
archivalPrivateKeyPath = "keys/tm1a.key"
storagePath = "qdata/constellation1"
```

**Comment by patrickmn** [comment]
They are not explicitly bound to each other, but are loosely coupled: by specifying the same config file for `constellation-node` and `geth`, the `geth` process queries the IPC socket (`tm1.ipc`) to send and receive encrypted payloads. Constellation takes care of encrypting the payloads and synchronizing them with other nodes before `geth` then creates Ethereum transactions referencing them.

You could choose to have multiple `geth` instances use the same `constellation-node` and config, or launch one per node, depending on your use case.
