### ISSUE TITLE
No Apparent Graceful Shutdown Signal

### ISSUE THREAD

**Issue by Freyert** [jpmorganchase/constellation#100]
When sending `SIGTERM` to constellation I expect the node to gracefully terminate.
Instead, the node continues to run and I must use a `SIGKILL` which forcefully terminates the process before it can gracefully shutdown.

Is there some other signal that's being expected?

**Comment by fixanoid** [comment]
@Freyert Constellation is no longer receiving upgrades. Please check if [Tessera](https://github.com/jpmorganchase/tessera/issues/) may be a better suited transaction manager for you.
