### ISSUE TITLE
Constellation Too many open files-quorum crash

### ISSUE THREAD

**Issue by andreaMWork** [jpmorganchase/constellation#101]
Hi all,
I am trying to run a small performance test on quorum, focusing on private transactions.
The test runs on an 8 nodes network.
The machines are hosted on AWS each node is an M5XL instance.
The test uses 4 nodes to insert those transactions private for the other 4 nodes.
When the load (trough Jmeter) reach about 50 TX/s constellation raise an issue:
`Network.Socket.accept: resource exhausted (Too many open files)`
We have been changing the number of open files without help.
limit.conf:
ubuntu soft nofile 1000000
ubuntu hard nofile 1000000
root soft nofile 1000000
root hard nofile 1000000
ubuntu - nproc 819200
root - nproc 819200
ubuntu - memlock unlimited
root - memlock unlimited

The output of sudo lsof | grep ipc :
`ghc_worke 20778 20789 ubuntu 25u unix 0xffff8803ea376800 0t0 6615462 node3.ipc type=STREAM`
multiplied by the number of open sockets ~1000

quorum crash with a SIGSEV error as below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x93b695]
 
goroutine 3723 [running]:
github.com/ethereum/go-ethereum/private/constellation.(*Client).ReceivePayload(0xc420254000, 0xc42d853700, 0x40, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/node.go:112 +0x135
github.com/ethereum/go-ethereum/private/constellation.(*Constellation).Receive(0xc42024e030, 0xc42d853700, 0x40, 0x40, 0xc42e2d0480, 0x1, 0x0, 0x0, 0x0)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:38 +0x13e
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc42e115b20, 0x116e040, 0xc42e2d0480, 0xc42e13ce40, 0xc42e115b20, 0xc42e19a5d8, 0xc42e2d0480, 0xc42e2d0480, 0xf74ea0)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:235 +0xdc6
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc42e2c1500, 0x116e040, 0xc42e2d0480, 0xc42e13ce40, 0xc34b8ade501462de, 0xa5cea460, 0xc42e2a5f00, 0x0, 0x0, 0x0, ...)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:138 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0xc4200e6000, 0xc4202f2000, 0x0, 0xc42e13ce40, 0xc42d715e00, 0xc42d715ef0, 0xc42d860480, 0xc42dac8750, 0xc42e13cbc0, 0x0, ...)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:121 +0x4e4
github.com/ethereum/go-ethereum/raft.(*work).commitTransaction(0xc42e11f560, 0xc42dac8750, 0xc4202f2000, 0xc42e13ce40, 0x9e2bbac6a4b2bc44, 0x0, 0x0, 0x0)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:400 +0x1a6
github.com/ethereum/go-ethereum/raft.(*work).commitTransactions(0xc42e11f560, 0xc42e11f7a0, 0xc4202f2000, 0x6f5d49, 0xc420038030, 0xe48100, 0x19eeb20, 0x0, 0x0, 0xc422fa5f28, ...)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:370 +0x28f
github.com/ethereum/go-ethereum/raft.(*minter).mintNewBlock(0xc4202df4a0)
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:305 +0xcf
github.com/ethereum/go-ethereum/raft.(*minter).mintingLoop.func1()
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:223 +0x3c
created by github.com/ethereum/go-ethereum/raft.throttle.func1
    /home/ubuntu/DoubleMachines/dtcc-quorum-top-level-project/distributed_setup/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:205 +0xc0
```

**Comment by fixanoid** [comment]
@andreaMWork for your test, did you build constellation locally?

**Comment by andreaMWork** [comment]
Hi @fixanoid I use the ubuntu binary usually but I wave tested building from master

**Comment by fixanoid** [comment]
@andreaMWork we suspect this issue is due to the outdated warp version that constellation was built with. If you are capable of building from source, please update the dependency to latest warp and retest. Otherwise, please wait for a pull / build.

**Comment by andreaMWork** [comment]
@fixanoid I did compile from master but the issue still appears.

**Comment by fixanoid** [comment]
@andreaMWork have you updated cabal/stack to the latest version of warp tho? Thats the update thats needed.

**Comment by fixanoid** [comment]
@andreaMWork please try this release: https://github.com/jpmorganchase/constellation/releases/tag/v0.3.5-build.1

**Comment by bts** [comment]
It looks like the code is potentially not closing file handles expeditiously when using the directory store backend for encrypted payloads.

The error is bubbling up from here:

https://github.com/jpmorganchase/constellation/blob/79a2a2a4396229543640bb64b1a9dbed2c1ae33b/Constellation/Node/Storage/Directory.hs#L40-L49

and then from the helper `writeFileLbs`:

https://github.com/jpmorganchase/constellation/blob/79a2a2a4396229543640bb64b1a9dbed2c1ae33b/Constellation/Util/File.hs#L44

This code is using lazy I/O. We should probably switch to use of a streaming library like streaming or pipes for this. Naive use of strict I/O here would not be great because we don't want to balloon memory usage of the process for large payloads.

**Comment by fixanoid** [comment]
@andreaMWork Please reopen if you are still experiencing this issue after 2.1 upgrade.
