### ISSUE TITLE
Always meet HandshakeFailed when I run Quorum example nodes

### ISSUE THREAD

**Issue by zhangds007** [jpmorganchase/constellation#104]
Hi, 

When I run Quorum examples， I always meet TLS HandshakeFailed. and I use default configuration and generate keypairs with constellation. Do you meet same issues? Can someone help? thanks a lot.

=========================================
01:08:31 [INFO] Log level is LevelDebug
01:08:31 [DEBUG] Configuration: Config 
    { cfgUrl = "https://192.168.1.7"
    , cfgPort = 21040
    , cfgWorkDir = Just "qdata/c1"
    , cfgSocket = Just "tm.ipc"
    , cfgOtherNodes = [ "https://192.168.1.7:21040/" ]
    , cfgPublicKeys = [ "tm.pub" ]
    , cfgPrivateKeys = [ "tm.key" ]
    , cfgAlwaysSendTo = []
    , cfgPasswords = Nothing
    , cfgStorage = "dir:storage"
    , cfgIpWhitelist = []
    , cfgTls = "strict"
    , cfgTlsServerCert = "tls-server-cert.pem"
    , cfgTlsServerChain = []
    , cfgTlsServerKey = "tls-server-key.pem"
    , cfgTlsServerTrust = "ca-or-tofu"
    , cfgTlsKnownClients = "tls-known-clients"
    , cfgTlsClientCert = "tls-client-cert.pem"
    , cfgTlsClientChain = []
    , cfgTlsClientKey = "tls-client-key.pem"
    , cfgTlsClientTrust = "ca-or-tofu"
    , cfgTlsKnownServers = "tls-known-servers"
    , cfgJustShowVersion = False
    , cfgJustGenerateKeys = []
    , cfgVerbosity = 3
    } 
02:18:10 [INFO] Utilizing 2 core(s)
02:18:10 [INFO] Constructing Enclave using keypairs [("tm.pub","tm.key")]
02:18:10 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
02:18:10 [INFO] Throwaway public key for self-sending: "vgCR8p2LmYECQLUqpFyM38jXjhohIe8BMP8ppJwhCAo="
02:18:10 [INFO] tls-server-cert.pem's fingerprint is "27:1D:10:C7:AE:3F:DB:C4:C9:D4:D8:9C:CF:B0:B4:CA:AD:17:7D:A5:87:B7:72:A2:9C:5E:92:F8:87:96:08:2D:5D:66:02:44:7C:04:69:F5:15:73:F1:DF:2D:AD:8A:86:3B:B8:06:29:FC:99:51:12:35:49:C7:92:A0:0B:27:CB"
02:18:10 [INFO] tls-client-cert.pem's fingerprint is "2C:F4:29:E1:0B:7B:EF:EF:2B:1E:F6:41:3B:71:D6:2E:FA:16:41:84:4C:47:7C:18:08:F8:4A:79:A7:65:0D:D5:27:59:BA:01:95:4B:82:C1:5F:26:86:99:A6:2F:DE:D4:A7:FC:D3:28:E8:74:D1:25:55:AF:E4:18:72:C0:3F:93"
02:18:10 [INFO] Private API listening on tm.ipc
02:18:10 [INFO] Public API listening on 0.0.0.0 port 21040 with whitelist: ["Disabled"]
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
02:18:10 [INFO] Node started
02:18:10 [DEBUG] Request from : ApiUpcheck; Response: ApiUpcheckR
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))

**Comment by namtruong** [comment]
Hi zhangds007,

At the moment constellation nodes will fail the SSL handshake if they run on a single VM with the same IP address (event with different ports), hence the certificate rejected message.

We are releasing a new version soon which will fix this issue. In the mean time I would suggest switching TLS configuration to off so you can have it working. This can be achieved by having tls=off in your config, and also changing the url from https:// to http://

Regards,
Nam
