### ISSUE TITLE
Integrating/integration constellation with hardware security modules (HSM) and/or Public Key Infrastructure (PKI)

### ISSUE THREAD

**Issue by nathanawmk** [jpmorganchase/constellation#105]
Hello, due to regulation requirements, there is a need to integrate constellation with hardware security modules (HSM) and Public Key Infrastructure (PKI).

What are some best/recommended ways and approaches? 

Nathan Aw (Singapore)

**Comment by fixanoid** [comment]
Closing as there are no plans to do this with Constellation. A new replacement that may allow some of this will be available shortly.
