### ISSUE TITLE
Private contract fails to create || [WARN] Error performing API request: ApiPush  || Save: Payload file already exists

### ISSUE THREAD

**Issue by nandakishorebhandari** [jpmorganchase/constellation#106]
While trying to create a private contract, Getting this error.

**Creating Private Contract:**
simpleContract.new(42, { from: web3.eth.accounts[1], data: bytecode, gas: 0x47b760, privateFor:["v0wYXz58AoaEv8Ky9fgx6PlaU*************"] })

**Web3 Browser Error:** 
{"jsonrpc":"2.0","id":12,"error":{"code":-32000,"message":"illegal base64 data at input byte 8"}}

 **Constellation Logs;** 
**14:47:25 [WARN] Error performing API request: ApiPush** ("\139\155?\250Tb\224\168\208\170\STX\208b\128\170\188-\191\CAN\207\180\188`y=\DEL;\190\213\140\133o","\247\143\181\227:\205[\205\ETB\170\167n,\DC3rU{\CANc\196\198b@\155\SOH\169u\211/\SI\t\138\199\241\248\234\255l\131\EOT\250\255\EOT\158k\166\233\190\229_\FSy,\226\251J h*\ENQ<\214\&7\229\NUL\168B\229\182\168S\240\&8\141\131\243\241\206\150\rQ\192\&9\DC4q\141\148,27\171[\GS\ETBl\136e~\156D\164B\168\EM`\208s\233w\166\163\198\rk\172\a\172H\144r%\n\ESC\209\132\167\229\249\196\146\196\133h\247p.r\t\147\&4\224N\186\STX\174>\131B\SI\174\242\166\176V8\244\150=w\GS\157\157m%\NULR@\135\&5\FS\202\183\251\222\223\DC4\187\246X\ESC\189\&1c\129\DEL\247:\211\145\222\153#\154\"y<\202\152\226\EOTk\SUBM\215Y\200\ESC\150\ETX!\EOT\128\"\t\170;\145\180\CAN\SI\192\239\161\ETX\193K\190^\r\136SC\208\US\DC4-\168X\228\FS\226po\234jM\US_\DLE\241\138\230$\195\147\169\236NPW\210\155v\EOT m_\128`\246h:\DLE\195\165\196D\166\129\222\&3)(;\251z\ENQ\240\SUB\155E\137\182\175\148lD\246%\ETB\186\140\&0\252\148\203m\132\144\166\&6j\168[\172;\n[\232\EMv\193\248\228K\164P\206r\170\241\159\191\249\173L\212\DLE\b\FS?\239\254S\211A\191ha\212$A\DLEmzbgi\196\186)\167\224\157\173\164Jw9\221\237\130\224'7\DC1\EOT","V_\148A\144\&2U\235v\157\227\b\254\184\172>\DC3\219n-\144y#\148",["\234\164\&16No\168al\\\EMk\231NE(w\203$_\228!#\STX=\DC25\158\179\192\242\248fD\153\251\DLE\216\166\182Iry\254\169\252 y"],"\DC2\DEL,?.\154\145q\CAN\v\ETB\195z\214\au\238O\131L7\205\252\245"); **save: Payload file already exists**

Note; Works fine with v0.2.0

**Comment by nandakishorebhandari** [comment]
I'm using quorum v2.0.0 https://github.com/jpmorganchase/quorum/releases/tag/v2.0.0 with Istanbul consenses.

**Comment by fixanoid** [comment]
Ahh, didnt see the `data` section you have. Please remove, that should help.

**Comment by nandakishorebhandari** [comment]
Thanks @fixanoid 

Can you tell, why it works with constellation v0.2.0? 
Then how to send the data while creating the smart contract?

**Comment by nandakishore96** [comment]
@fixanoid, I appreciate, if you could share your comments for

Can you tell, why it works with constellation v0.2.0?
Then how to send the data while creating the smart contract?
