### ISSUE TITLE
constellation-node: Network.Socket.bind: invalid argument (File name too long)

### ISSUE THREAD

**Issue by xhw1** [jpmorganchase/constellation#109]
I used the following `constellation-start.sh` script in a docker container on a mac, there is no tm.ipc in workdir, and it will stuck in the while loop:
```bash
set -u
set -e

DDIR="./qdata/c"

mkdir -p ./qdata/logs

rm -f "$DDIR/tm.ipc"
CMD="constellation-node --url=https://$NODE_HOST_NAME:9001/ --port=9001 --workdir=$DDIR --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://node:9001/"
echo "$CMD >> ./qdata/logs/constellation.log 2>&1 &"
$CMD >> "./qdata/logs/constellation.log" 2>&1 &

DOWN=true
while $DOWN; do
    sleep 0.1
    DOWN=false
	if [ ! -S "$DDIR/tm.ipc" ]; then
        DOWN=true
	fi
done
```

I check the logs, there is a error message at the bottom:
```
17:15:31 [INFO] Log level is LevelWarn
17:15:32 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
17:15:32 [WARN] No TLS certificate or key found; generating tls-client-cert.pem/tls-client-key.pem
17:15:33 [WARN] No TLS certificate or key found; generating tls-server-cert.pem/tls-server-key.pem
Unlocking tm.key
Unlocked tm.key
constellation-node: Network.Socket.bind: invalid argument (File name too long)
```
When I used the script in the same docker container on a linux machine it worked fine. What can I adjust for mac?
Thank you so much for you time.

**Comment by trung** [comment]
@xhw1 what is your full path to your `qdata` directory?

`ipc` is unix socket file and it seems [there's a limit](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars) on the file path.

**Comment by xhw1** [comment]
> @xhw1 what is your full path to your `qdata` directory?
> 
> `ipc` is unix socket file and it seems [there's a limit](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars) on the file path.

Thank you so much! Moving the folder to a shorter path solved the problem.
