### ISSUE TITLE
How to generate node keys

### ISSUE THREAD

**Issue by jaguarg** [jpmorganchase/constellation#11]
Hi, 

Please can you explain how I can generate a private / public key for my constellation node ? 
Same for the archival Public / Private Key ? 

Many thanks

**Comment by patrickmn** [comment]
`constellation-enclave-keygen <key name 1> <key name 2> <...>`

Optionally set a password for each, then point to the generated .pub/.key files in the Constellation config file.

(Please note that archival keys have been removed from master and will be removed in the next release.)
