### ISSUE TITLE
Certificate validation failed error when using tls CA trust mode

### ISSUE THREAD

**Issue by namtruong** [jpmorganchase/constellation#111]
Constellation nodes are failing to connect with each other via tls communication using CA trust mode.

Error message `HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))`

Config

url = "http://QUORUM_NODE_ADDRESS:9001/"
port = 9001
workdir = "QUORUM_DIR"
socket = "/data/constellation.ipc"
othernodes = [CONSTELLATION_NODES]
publickeys = ["constellation.pub"]
privatekeys = ["constellation.key"]
alwayssendto = []
storage = "dir:storage"
verbosity = 4
tls = "strict"
tlsservercert = "tls_server.crt"
tlsserverchain = ["root_ca.crt"]
tlsserverkey = "tls_server.key"
tlsservertrust = "ca"
tlsclientcert = "tls_client.crt"
tlsclientchain = ["root_ca.crt"]
tlsclientkey = "tls_client.key"
tlsclienttrust = "ca"

**Comment by patrickmn** [comment]
Please make sure the CA is in the system certificate store for the client/server. The chains are merely the path the client/server present to the other side; the other side checks that against the root authorities it knows.

You can override where Constellation looks for system certificates (usually /etc/ssl/certs) with the `SYSTEM_CERTIFICATE_PATH` environment variable.
