### ISSUE TITLE
Can't load the constellation

### ISSUE THREAD

**Issue by flyq** [jpmorganchase/constellation#113]
```
$ constellation-node 
constellation-node: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory
```

I used https://github.com/jpmorganchase/constellation/releases/download/v0.3.5-build.1/constellation-0.3.5-ubuntu1604.tar.gz

**Comment by fixanoid** [comment]
You need to install prequisites from this list: https://github.com/jpmorganchase/constellation#prerequisites
