### ISSUE TITLE
Constellation party caching issue

### ISSUE THREAD

**Issue by fixanoid** [jpmorganchase/constellation#115]
Hi guys,

I'm having a little problem with the constellation sync process. Old/wrongs urls are propagated and I can't delete them. I'm hoping that the protocol will remove them automatically because the process of sync fails several times, but it doesn't.

[WARN] Synchronization failed: InvalidUrlException "http://10.107.7.118:9000partyinfo" "Invalid URL"

My question is where the URLs list is stored and how to remove it?

_Originally posted by @fabianoa in https://github.com/jpmorganchase/constellation/issues/77#issuecomment-459740910_

**Comment by namtruong** [comment]
@fabianoa you should be able to fix this just by restarting the network (after correct the peer url in your config).

Detecting stale connection and removing them from the network automatically is something we're actively working on.

**Comment by fabianoa** [comment]
@namtruong  I just tried to restart some nodes after fixing it, but doesn't work. The old URL still remain on the replication process.  I guess I  have to restart all node at the same time. That's what you propose, okay? However, on big decentralized networks is hard-working to do this.

Thanks,

**Comment by fixanoid** [comment]
@fabianoa you'd need to bring down the entire network and then start it back up -- if you do one by one, the nodes that are restarted attempt to resync with other nodes partyinfo and thats where the incorrect p2p list is passed.
