### ISSUE TITLE
SendRaw Transaction 

### ISSUE THREAD

**Issue by jiten-balla** [jpmorganchase/constellation#116]
SendRawTransaction is not working in constellation. Any plans for supporting this feature in constellation. As per tessera document its supporting SendRawTransaction feature from 0.8.

**Comment by fixanoid** [comment]
At the moment, c11n development is frozen and there is no intention to add missing features from Tessera as part of our core development efforts. c11n will remain our reference implementation of a private transaction manager and we're likely to incentivize continued development for it by the community at a future date.

**Comment by jiten-balla** [comment]
I will try to implement and raise pull request thanks for the reply.
