### ISSUE TITLE
Add a command-line switch to specify the log level

### ISSUE THREAD

**Issue by jaguarg** [jpmorganchase/constellation#12]
I would like to investigate a problem. what is the switch to set log level to verbose ? 

I am trying to figure out why my constellation node is not generating the socket ipc file

**Comment by patrickmn** [comment]
There is currently no such switch, although it should be added in the next release.

The most likely reason is that the folder defined in the configuration file doesn't exist prior to launching constellation. On Mac, we've seen a similar issue likely related to file limits that was resolved by rebooting the machine.

**Comment by jaguarg** [comment]
Hi Patrick, thank you for your reply. 
I just moved my running folder to a local folder (rather than a vagrant host mount) and it's launching ok now.

**Comment by patrickmn** [comment]
In progress: https://github.com/jpmorganchase/constellation/pull/19

**Comment by patrickmn** [comment]
Merged: https://github.com/jpmorganchase/constellation/commit/4b4ba6003baf01705ec9f7d843baeae3b37f9a94

This will go in the 0.0.2 release, but can be used now by compiling from source pulled from master.
