### ISSUE TITLE
may you release this program based on ubuntu20.04?

### ISSUE THREAD

**Issue by dawnFromDark** [jpmorganchase/constellation#120]
dear developers,this program can not run on ubuntu 20.04,it depend so man libraries and the ubuntu20.04 can not contain these, may you re-compile it and release it, i come from china, therefore,it 's very diffcult to compile because the firewall, please.

**Comment by fixanoid** [comment]
Hi @dawnFromDark c11n is provided as a simplest reference implementation to see how c11n should operate. It is not however a client we're continuing to support, so please look into @ConsenSys/tessera instead.
