### ISSUE TITLE
Add peer management APIs

### ISSUE THREAD

**Issue by patrickmn** [jpmorganchase/constellation#15]
- Ability to trigger immediate resynchronization
- Ability to add a peer (which for whatever reason isn't reaching out to us, e.g. empty initial config) at runtime

**Comment by vietlq** [comment]
What's the consensus for adding a peer? What if other Constellation nodes do not agree with the decision?

**Comment by fixanoid** [comment]
@vietlq constellation is no longer receiving updates at this point. Please reopen on (Tessera)[https://github.com/jpmorganchase/tessera/issues/] to check on the design as this feature has already been completed.
