### ISSUE TITLE
Feature request: Windows support

### ISSUE THREAD

**Issue by patrickmn** [jpmorganchase/constellation#2]

**Comment by gossion** [comment]
Hi @patrickmn , is this feature ready in quorum 2.0.0? and how to build a windows constellation?

**Comment by patrickmn** [comment]
@gossion, the milestone is 2.0.0 of Constellation, not Quorum.

There are a few things that preclude (non-WSL) Windows support in both Quorum and Constellation, one being that they communicate via UNIX socket for security-sensitive IPC.

Are you dependent on native Windows support?

**Comment by gossion** [comment]
Thanks.  Could Quorum geth on Windows talk with Constellation on Linux?
We have built Quorum geth on Windows, and want to run nodes on Windows.

**Comment by patrickmn** [comment]
Are you able to use the Windows Subsystem for Linux?

**Comment by gossion** [comment]
Running it on Windows Subsystem for Linux is not our first option, we want to run it as fully windows.
Currently since Constellation is not windows supported, we might consider running geth on Windows, and put Constellation on Linux, is it doable?

**Comment by patrickmn** [comment]
I'm asking because we've had reports of Quorum/Constellation running well on it, so at least it's an option.

Yes, that would be doable, albeit with a small change: Currently the IPC between Quorum and Constellation happens over a UNIX socket for security reasons, so we'd need to add support for a TCP IPC socket. (There may be a few more changes needed -- hopefully small.)

PS: Quorum itself does not have full Windows support either. If you're planning to use ZSL, for example, you should know that that will be Linux-only for the immediate future.

**Comment by gossion** [comment]
Thanks for explaining, @patrickmn . Seems a long way to go if we want to run Quorum and Constellation on Windows.

**Comment by cartazio** [comment]
no windows support is planned at this time
