### ISSUE TITLE
`invalid padding` error

### ISSUE THREAD

**Issue by hermanjunge** [jpmorganchase/constellation#21]
I checked for the obvious, namely, tampering the `pub` base64 by adding some characters at the start. The error, changes to `invalid base64 encoding near offset 44`. Also I verified that I was using the same version `constellation-enclave-keygen`, and finally, tried to use keys from `quorum-examples` just in case.

**DISCLAIMER**: Pretty sure is a layer 8 error, but I cannot see it after two hours of fiddling. Kindly request for help.

* Commit is

```
commit 4b4ba6003baf01705ec9f7d843baeae3b37f9a94
Author: Patrick Mylund Nielsen <patrick@patrickmn.com>
Date:   Fri Mar 24 12:09:11 2017 -0400
```

* Log obtained

```
./constellation-node ethereum/constellation-conf

2017 Mar-28 10:36:12663291 [INFO] Log level is LevelDebug
2017 Mar-28 10:36:12663469 [DEBUG] Configuration: Config {cfgUrl = "http://10.24.0.4:22000/", cfgPort = 22000, cfgSocket = Just "/home/banketh/ethereum/constellation.ipc", cfgOtherNodes = ["http://10.24.0.5:22000/, http://10.24.0.8:22000/, http://10.24.0.7:22000/"], cfgPublicKeys = ["/home/banketh/ethereum/constellation-pub"], cfgPrivateKeys = ["/home/banketh/ethereum/constellation-prv"], cfgPasswords = Nothing, cfgStorage = "/home/banketh/ethereum/constellation", cfgIpWhitelist = [], cfgJustShowVersion = False, cfgVerbosity = 3}
2017 Mar-28 10:36:12663554 [INFO] Utilizing 1 core(s)
2017 Mar-28 10:36:12663722 [INFO] Constructing Enclave using keypairs [("/home/banketh/ethereum/constellation-pub","/home/banketh/ethereum/constellation-prv")]
constellation-node: fromShowRight: Got Left: "invalid padding"
CallStack (from HasCallStack):
  error, called at ./Constellation/Util/Either.hs:14:28 in constellation-0.1.0.0-IsiykKpPlVs3yKQYw1hA4n:Constellation.Util.Either
```

* Command

```
./constellation-node ethereum/constellation-conf
```

* `constellation-conf`

```
# Externally accessible URL for this node (this is what's advertised)
url = "http://10.24.0.4:22000/"

# Port to listen on for the public API
port = 22000

# Socket file to use for the private API / IPC
socket = "/home/banketh/ethereum/constellation.ipc"

# Initial (not necessarily complete) list of other nodes in the network.
# Constellation will automatically connect to other nodes not in this list
# that are advertised by the nodes below, thus these can be considered the
# "boot nodes."
othernodes = ["http://10.24.0.5:22000/", "http://10.24.0.8:22000/", "http://10.24.0.7:22000/"]

# The set of public keys this node will host
publickeys = ["/home/banketh/ethereum/constellation-pub"]

# The corresponding set of private keys
privatekeys = ["/home/banketh/ethereum/constellation-prv"]

# Optional file containing the passwords to unlock the given privatekeys
# (one password per line -- add an empty line if one key isn't locked.)
# passwords = "passwords"

# Where to store payloads and related information
storage = "/home/banketh/ethereum/constellation"

# Optional IP whitelist for the external API. If unspecified/empty,
# connections from all sources will be allowed (but the private API remains
# accessible only via the IPC socket above.) To allow connections from
# localhost when a whitelist is defined, e.g. when running multiple
# Constellation nodes on the same machine, add "127.0.0.1" and "::1" to
# this list.
# ipwhitelist = ["10.0.0.1", "2001:0db8:85a3:0000:0000:8a2e:0370:7334"]

# Verbosity level (each level includes all prior levels)
#   - 0: Only fatal errors
#   - 1: Warnings
#   - 2: Informational messages
#   - 3: Debug messages
verbosity = 3
```

* `constellation-pub`

```
UVSeNgQA2WJSZVoUAi5v2Ebu0aSc18QW2juW/yBSDzI=
```

* `constellation-prv`

```
{"data":{"bytes":"PQv0IkX0HR/qxv7v/3bkqLgqAb3EuNYl3LLDwHWyCm0="},"type":"unlocked"}
```

**Comment by patrickmn** [comment]
I can reproduce it with the keypair you gave, using both the latest commit and `c3031121fffcd118d620c51a763266f782d99300`, which is from before we changed the Argon2 library and upgraded to GHC 8.

I cannot reproduce with any of the keys from https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes/keys or a newly generated key pair with either the old or new `constellation-node`.

This does seem strange. Has this key pair ever worked? The `invalid padding` error is definitely from the `base64-bytestring` library.

**Comment by hermanjunge** [comment]
> Has this key pair ever worked

Never tried them in older versions. The weird part for me is that I can
reproduce with the 7 nodes keys. Also, 3 other pairs failed.

I ran `od` just to test whether there were some sinister `\n`, didn't found
anything. Later, I am checking with different commits of constellation.
Will report soon.

On Mar 28, 2017 21:13, "Patrick Mylund Nielsen" <notifications@github.com>
wrote:

I can reproduce it with the keypair you gave, using both the latest commit
and c3031121fffcd118d620c51a763266f782d99300, which is from before we
changed the Argon2 library and upgraded to GHC 8.

I cannot reproduce with any of the keys from https://github.com/
jpmorganchase/quorum-examples/tree/master/examples/7nodes/keys or a newly
generated key pair with either the old or new constellation-node.

This does seem strange. Has this key pair ever worked? The invalid padding
error is definitely from the base64-bytestring library.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/jpmorganchase/constellation/issues/21#issuecomment-289839822>,
or mute the thread

**Comment by patrickmn** [comment]
Yeah, if I had to guess, I'd suspect file system funkiness (OS X?) or possibly a buggy version of `base64-bytestring` (if you're using `cabal` and not `stack` to build `constellation`.)

Do you get the error with `7nodes/keys/tm1.[pub/key]` using the latest commit installed with `stack install`?

**Comment by hermanjunge** [comment]
This one was a super tricky one, but obvious in retrospective: I blame myself for being jet-lagged, and I _partially_ blame haskell, hehe.

So we have this slight difference, between a file made with `constellation-enclave-keygen`, and a file made with `bash` or `vim`, where you get the contents of the keygen, and dump them into a file. For example

```
echo ssutrZ/U1DJ0uK0dE8AMHLUqZgrzNgobiDb/L0yxoxg= > 1.pub
```

Which I was doing for my suite of quorum tools.

The difference is the newline character added at the end `\x0A`

```root@2f0e474b94c8:/execs# xxd copied-using-bash-or-vim
0000000: 4175 5866 4463 3749 2b33 6b61 5262 646d  AuXfDc7I+3kaRbdm
0000010: 3367 3467 6766 6978 5a53 6d6e 717a 4656  3g4ggfixZSmnqzFV
0000020: 7944 6849 6943 5148 7578 343d 0a          yDhIiCQHux4=.

root@2f0e474b94c8:/execs# xxd straight-from-constellation-enclave
0000000: 4175 5866 4463 3749 2b33 6b61 5262 646d  AuXfDc7I+3kaRbdm
0000010: 3367 3467 6766 6978 5a53 6d6e 717a 4656  3g4ggfixZSmnqzFV
0000020: 7944 6849 6943 5148 7578 343d            yDhIiCQHux4=
```

The haskell library won't ignore the newline value and will complain in both the public and private keys.

Let's do the exercise with both keys _wrong_ then iterate until we get it right.

```
[root@dev-env-00 ~]$ xxd constellation-pub
0000000: 7373 7574 725a 2f55 3144 4a30 754b 3064  ssutrZ/U1DJ0uK0d
0000010: 4538 414d 484c 5571 5a67 727a 4e67 6f62  E8AMHLUqZgrzNgob
0000020: 6944 622f 4c30 7978 6f78 673d 0a         iDb/L0yxoxg=.

[root@dev-env-00 ~]$ xxd constellation-prv
0000000: 7b22 6461 7461 223a 7b22 6279 7465 7322  {"data":{"bytes"
0000010: 3a22 7851 616b 6841 6655 3134 3563 776a  :"xQakhAfU145cwj
0000020: 4f57 6363 594e 6546 3657 3935 5073 5347  OWccYNeF6W95PsSG
0000030: 3146 6e38 4871 7954 5156 6371 733d 227d  1Fn8HqyTQVcqs="}
0000040: 2c22 7479 7065 223a 2275 6e6c 6f63 6b65  ,"type":"unlocke
0000050: 6422 7d0a                                d"}.
```

Executing will output

```
[root@dev-env-00 ~]$ ./constellation-node .constellation-conf

2017 Mar-31 07:40:57543789 [INFO] Log level is LevelWarn
constellation-node: fromShowRight: Got Left: "invalid padding"
CallStack (from HasCallStack):
  error, called at ./Constellation/Util/Either.hs:14:28 in constellation-0.1.0.0-IsiykKpPlVs3yKQYw1hA4n:Constellation.Util.Either
```

Let's fix both keys (using `perl` and `sed`)

```
[root@dev-env-00 ~]$ perl -ne 's/\x0A//g; print' < constellation-pub > _constellation-pub && mv _constellation-pub constellation-pub && xxd constellation-pub

0000000: 7373 7574 725a 2f55 3144 4a30 754b 3064  ssutrZ/U1DJ0uK0d
0000010: 4538 414d 484c 5571 5a67 727a 4e67 6f62  E8AMHLUqZgrzNgob
0000020: 6944 622f 4c30 7978 6f78 673d            iDb/L0yxoxg=
```

Executing

```
[root@dev-env-00 ~]$ ./constellation-node ./constellation-conf

2017 Mar-31 07:53:50975280 [INFO] Log level is LevelWarn
Unlocking /home/banketh/ethereum/constellation-prv
Unlocked /home/banketh/ethereum/constellation-prv
```

Works? Let's switch the configuration `verbosity` value to `3`

```
[root@dev-env-00 ~]$ ./constellation-node ./constellation-conf

2017 Mar-31 07:57:26549733 [INFO] Log level is LevelDebug
2017 Mar-31 07:57:26550134 [DEBUG] Configuration: Config {cfgUrl = "http://10.24.0.4:22000/", cfgPort = 22000, cfgSocket = Just "/root/constellation.ipc", cfgOtherNodes = ["http://10.24.0.5:22000/, http://10.24.0.8:22000/, http://10.24.0.7:22000/"], cfgPublicKeys = ["/root/constellation-pub"], cfgPrivateKeys = ["/root/constellation-prv"], cfgPasswords = Nothing, cfgStorage = "/root/constellation", cfgIpWhitelist = [], cfgJustShowVersion = False, cfgVerbosity = 3}
2017 Mar-31 07:57:26550217 [INFO] Utilizing 1 core(s)
2017 Mar-31 07:57:26550380 [INFO] Constructing Enclave using keypairs [("/root/constellation-pub","/root/constellation-prv")]
Unlocking /root/constellation-prv
Unlocked /root/constellation-prv
2017 Mar-31 07:57:26550648 [INFO] Initializing storage /root/constellation
2017 Mar-31 07:57:27020759 [INFO] External API listening on 0.0.0.0 port 22000 with whitelist: ["Disabled"]
2017 Mar-31 07:57:27020661 [INFO] Node started
2017 Mar-31 07:57:27022757 [INFO] Internal API listening on /root/constellation.ipc
```

## Conclusions

* Add a note in the documentation of being careful with copying the keys, as some OS add ending characters, and `constellation-node` won't parse them.
* Maybe process the string before trying to parse it? 😬 

Is your call @patrickmn whether we close this issue or not. Thank you for your response.

**Comment by patrickmn** [comment]
Oh, doh. At least that's an easy fix. Is the problem solved with https://github.com/jpmorganchase/constellation/commit/8437fc9ac7c339833d77e6dcdc6db12f43f30dc9 ?

The private key shouldn't be affected since \n is ignored in JSON, just not in Base64.
