### ISSUE TITLE
Suggest to provide way to remove data from DB by key, or purge old data

### ISSUE THREAD

**Issue by kanelai** [jpmorganchase/constellation#22]
Otherwise the DB would grow infinitely.

**Comment by kanelai** [comment]
Or is my expectation correct? Is this storage treated just like the blockchain storage for Quorum and should't be removed? Or it can be used as a way to transfer transaction attachments (e.g. files) ??

**Comment by patrickmn** [comment]
No, this is definitely a valid request. Constellation should have different storage strategies to choose from and/or methods to enact them depending on the use case.

Right now, the data is kept around forever unless you spin down constellation and use BerkeleyDB tools to remove keys.

**Comment by kanelai** [comment]
Glad that this enhancement is being considered. Actually I was studying the possibility to use Constellation along with another Blockchain (not Quorum), using it as an off-chain mechanism to safely transfer data and attachments between parties. But so far I see a few challenges:
1. Data is kept forever, which you've addressed already 
2. Binary data need to be encoded in base64 before transfer, which is not efficient for transfer 
3. Seems the API would fail if the payload is too large

**Comment by kanelai** [comment]
It's always a challenge in most Blockchain implementations (except Corda) to do p2p transfer for those data not suitable to be stored on chain...

**Comment by patrickmn** [comment]
I think we can accommodate that with a few simple additions to the API:

  - A `delete(key)` method
  - A `sendraw` endpoint that extracts `from` and `to` from the HTTP headers and lets the body be an `octet-stream` (with appropriate `Content-Length`) to avoid JSON and Base64 overhead (Constellation only uses those formats for the API, not storage or transfer between peer nodes.)
  - Corresponding `receiveraw` method

This could be done pretty soon if it'd be helpful.

**Comment by kanelai** [comment]
This looks good. Sad that I'm not able to help to implement. Haskell is really not straight-forward to me:(

**Comment by conor10** [comment]
@patrickmn I could help with the implementation if you like?

**Comment by patrickmn** [comment]
@conor10 Sure, go for it!

**Comment by kanelai** [comment]
Thanks both!

**Comment by patrickmn** [comment]
POSTing Internal API's /delete with body `{"key": "key"}` should now work.

(The caveat is that, for now, the Internal API is only accessible via UNIX Domain Socket. See https://github.com/jpmorganchase/quorum/blob/master/private/constellation/node.go for an example of how to hit it. In the future this restriction--socket only for internal API--will probably be relaxed.)
