### ISSUE TITLE
Allow configuration of constellation, geth and bootnode using FQDN vs. IP address

### ISSUE THREAD

**Issue by moderation** [jpmorganchase/constellation#23]
I've been working on standing up the [7 node example](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes) on Mesosphere DC/OS.  Currently the configuration used to launch Constellation and geth requires addresses in the form of IP address. In cloud orchestration environments like DC/OS and Kubernetes the containers launch can have short lives and move around throughout the cluster. IP addresses have less relevance and the containers are usually given names as part of the Service Discovery mechanism.

For example on DC/OS using IP per Container the containers are given names in the format of `myapp-subgroup-outergroup.marathon.containerip.dcos.thisdcos.directory` ([documentation](https://dcos.io/docs/1.8/usage/service-discovery/dns-overview/#service-discovery-options))

[tm2.conf](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/tm2.conf) requires IP address:

```
url = "http://127.0.0.1:9001/"
port = 9001
socketPath = "qdata/tm2.ipc"
otherNodeUrls = ["http://127.0.0.1:9000/"]
publicKeyPath = "keys/tm2.pub"
privateKeyPath = "keys/tm2.key"
archivalPublicKeyPath = "keys/tm2a.pub"
archivalPrivateKeyPath = "keys/tm2a.key"
storagePath = "qdata/constellation2"
```

Ideally you should be able to specify by the FQDN understood by the container orchestrator DNS:

```
url = "http://node2-quorum.marathon.containerip.dcos.thisdcos.directory:9001/"
port = 9001
socketPath = "qdata/tm2.ipc"
otherNodeUrls = ["http://node1-quorum.marathon.containerip.dcos.thisdcos.directory:9000/"]
publicKeyPath = "keys/tm2.pub"
privateKeyPath = "keys/tm2.key"
archivalPublicKeyPath = "keys/tm2a.pub"
archivalPrivateKeyPath = "keys/tm2a.key"
storagePath = "qdata/constellation2"
```
Similarly in the start.sh script fails when using FQDN over IP address:

```
BOOTNODE_ENODE=enode://61077a284f5ba7607ab04f33cfde2750d659ad9af962516e159cf6ce708646066cd927a900944ce393b98b95c914e4d6c54b099f568342647a1cd4a262cc0423@[127.0.0.1]:33445

GLOBAL_ARGS="--bootnodes $BOOTNODE_ENODE --networkid $NETID --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum"
```

Should be
```
BOOTNODE_ENODE=enode://61077a284f5ba7607ab04f33cfde2750d659ad9af962516e159cf6ce708646066cd927a900944ce393b98b95c914e4d6c54b099f568342647a1cd4a262cc0423@[bootnode-quorum.marathon.containerip.dcos.thisdcos.directory]:33445

GLOBAL_ARGS="--bootnodes $BOOTNODE_ENODE --networkid $NETID --rpc --rpcaddr node1-quorum.marathon.containerip.dcos.thisdcos.directory --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum"
```
(This example needs to change to set node specific rpcaddr based on IP per container deployments).

**Comment by patrickmn** [comment]
Constellation does not require `url` or `otherNodeUrls` to be IP addresses. They can be FQDNs.

Ethereum (and thus Quorum) is another story: https://github.com/ethereum/wiki/wiki/enode-url-format

I would suggest raising the request for DNS names in enode URLs upstream (though there may be a good reason for that design decision.)

**Comment by moderation** [comment]
Thanks for the link. There are related [issues](https://github.com/ethereum/go-ethereum/issues?utf8=%E2%9C%93&q=is%3Aissue%20enode%20dns).
