### ISSUE TITLE
Document configuration file changes and conversion

### ISSUE THREAD

**Issue by vjrantal** [jpmorganchase/constellation#33]
The feature is documented as follows:

```
"Comma-separated list of paths to public keys that are always included as recipients (these must be advertised somewhere)"
```

However, using that syntax will not result into adding the recipients as expected when also `privateKeyPath` is set.

An example config file to reproduce the problem is as follows:

```
url = "http://192.168.0.158:9000/"
port = 9000
socketPath = "qdata/tm1.ipc"
otherNodeUrls = ["http://192.168.0.194:9001/"]
publicKeyPath = "keys/tm1.pub"
privateKeyPath = "keys/tm1.key"
alwayssendto = ["keys/tm3.pub"]
storagePath = "qdata/constellation1"
verbosity = 3
```

Above results into follow debug print:

```
2017 May-31 08:23:16334502 [DEBUG] Configuration: Config {cfgUrl = "http://192.168.0.158:9000/", cfgPort = 9000, cfgSocket = Just "qdata/tm1.ipc", cfgOtherNodes = ["http://192.168.0.194:9001/"], cfgPublicKeys = ["keys/tm1.pub"], cfgPrivateKeys = ["keys/tm1.key"], cfgAlwaysSendTo = [], cfgPasswords = Nothing, cfgStorage = "qdata/constellation1", cfgIpWhitelist = [], cfgJustShowVersion = False, cfgJustGenerateKeys = [], cfgVerbosity = 3}
```

Observe in above that `cfgAlwaysSendTo` is an empty array.

**Comment by vjrantal** [comment]
Actually, now that I read the source code more carefully, it looks like the expectation is that `privateKeyPath` is not used anymore, but instead, a flag called `privatekeys` is used. In that case, the code path will be different and the value from `alwayssendto` will be picked up.

So my sample configuration should be changed to:

```
url = "http://192.168.0.158:9000/"
port = 9000
socket = "qdata/tm1.ipc"
othernodes = ["http://192.168.0.194:9001/"]
publickeys = ["keys/tm1.pub"]
privatekeys = ["keys/tm1.key"]
alwayssendto = ["keys/tm3.pub"]
storage = "qdata/constellation1"
verbosity = 3
```

I am closing this issue since it doesn't really require code changes, but I think this should be documented when a backwards-incompatible release is made.

**Comment by patrickmn** [comment]
Indeed, this is due to the mixing of the old and new config format (which as you correctly pointed out is determined by the presence of privateKeyPath.) That handling could be more sophisticated, trying every old field before trying every new field, rather than just trying to figure out if it's the old format or new format.

I plan to write a guide on these changes by the time the next Constellation release is issued.

**Comment by patrickmn** [comment]
Hopefully this will suffice: https://github.com/jpmorganchase/constellation/blob/master/CHANGELOG.md#010---2017-06-06
