### ISSUE TITLE
Provide RPM (CentOS/RHEL) and Deb (Debian/Ubuntu) repositories for binaries

### ISSUE THREAD

**Issue by patrickmn** [jpmorganchase/constellation#40]

**Comment by elopio** [comment]
It's very easy to package constellation in a [snap](https://snapcraft.io), and publish it in the Ubuntu store.

However, I wasn't sure if by itself is useful. I proposed the metadata to package quorum, which includes constellation:

https://github.com/jpmorganchase/quorum/pull/183
