### ISSUE TITLE
constellation-node not running

### ISSUE THREAD

**Issue by ztajy** [jpmorganchase/constellation#43]
Hi,
    My constellation-node is not running,run 'constellation-node --version',prompt ‘constellation-node: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by constellation-node)’。
    My operating system is Ubuntu 14.04 LTS (GNU/Linux 3.13.0-123-generic x86_64)，already run ‘apt-get install libdb-dev libleveldb-dev libsodium-dev zlib1g-dev libtinfo-dev’。
    Run ldd，prompt：
/home/quorum/constellation-0.1.0-ubuntu1604/constellation-node: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /home/quorum/constellation-0.1.0-ubuntu1604/constellation-node)
        linux-vdso.so.1 =>  (0x00007ffee9fa2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0af6f97000)
        libsodium.so.18 => /usr/local/libsodium-1.0.12/src/libsodium/.libs/libsodium.so.18 (0x00007f0af6d2b000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0af6b12000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f0af68e9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0af66e1000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0af64de000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0af62da000)
        libdb-5.3.so => /usr/lib/x86_64-linux-gnu/libdb-5.3.so (0x00007f0af5f38000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f0af5cc4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0af59be000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0af57a0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0af558a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0af51c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0af729b000)
Please help，tks。

**Comment by cartazio** [comment]
generally this sort of linker error means that theres some mismatch between the binary and the platform you're running on, or something to that effect. closing for now. When this happens, the best fix is to build a binary native to that linux distro
