### ISSUE TITLE
Sender cannot be a recipient check prevents private transaction recovery

### ISSUE THREAD

**Issue by conor10** [jpmorganchase/constellation#47]
Although the following [issue](https://github.com/jpmorganchase/quorum/issues/97) touches on this, I thought it useful to create a more specific issue to discuss potential solutions to this problem.

The [safeBeforeNM](https://github.com/jpmorganchase/constellation/blob/b05e0568e39f7d3b682a48fc0d53494a109e8f8f/Constellation/Enclave/Payload.hs#L55) is used both in processing new transactions and retrieving existing in Constellation to ensure that the sender public key is not the same as the intended recipent(s) public key (i.e. the _privateFor_ address on transactions)

During the processing of receive requests from geth nodes (i.e. new private transaction) , this has the knock-on effect of preventing private transactions from being loaded into the private database when a node has to be run up fresh (this transaction retrieval happens [here](https://github.com/jpmorganchase/constellation/blob/e59c256931599f2e4ac66c7b6e663db27f23c65a/Constellation/Enclave.hs#L73)).

For example, we have two geth instances (_geth1_ & _geth2_) and their corresponding Constellation instances (_tm1_ & _tm2_), configured as follows:

```
tm1PubKey = "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="
tm2PubKey = "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="
```

We then send a transaction from geth1, with _privateFor_ set to _tm2PubKey_

ApiSend request goes from _geth1_ to _tm1_:

```
2017 Aug-07 15:36:58931107 [DEBUG] Request from : ApiSend
 (Send {sreqPayload = "\t^\167\179\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\202\132\&5i\227BqD\206\173^
MY\153\163\208\204\249+\142\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULd", sreqFrom = "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=", sreqTo = ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="]}); Response: ApiSendR (SendResponse {sresKey = "mcQktPbaCa+xFUPMP0rGRzROmP/4zWxfpUWkXeET0Tj/b9D5wuqTmYXQIj/KYFdgsZSAE+7WQws0Sayczwz8FQ==“})
```

Corresponding _ApiPush_ and _ApiReceive_ received by _tm2_:

```
2017 Aug-07 15:36:58927546 [DEBUG] Request from 127.0.0.1:58378: ApiPush ("\ENQB\222G\194rQhb\186\224\140S\241\203\ETXD9\167\&9\CANO\231\a \141\217(\ETB\178\220\SUB","\NAKs2~\131\197\&4O\176\&9>C\177\227\231e\254\174k\223\243I\DC1\201\n\225\193\216#\162Q\139c\236\143\183\b5y\227\193=\235f\247\208\255\SOa`\247p\129\238\199\212)5\168Yt\EM*D\209w\242-\170\147K\148\CAN(\192\181\238\198\210\"\SO\170\&6\158","\244\147G\234\129g2\135\233\DLEP\188\252)\202\STX@\157\196U\147\196I0",["\209\142\212\186\169tq*|p\194\142\237\164j\154~\151\202\230\142\ENQ\152\186\a+\DC4\ESC\146]\232d\a'\174\158\193\232\191\a\167\DC29?\165\195\EM\b"],"C#a\141fE\tuK\181\a\253\210L?\140\146\213s9\190'\147\181"); 
Response: ApiPushR "mcQktPbaCa+xFUPMP0rGRzROmP/4zWxfpUWkXeET0Tj/b9D5wuqTmYXQIj/KYFdgsZSAE+7WQws0Sayczwz8FQ=="

2017 Aug-07 15:36:58950493 [DEBUG] Request from : ApiReceive (Receive {rreqKey = "
mcQktPbaCa+xFUPMP0rGRzROmP/4zWxfpUWkXeET0Tj/b9D5wuqTmYXQIj/KYFdgsZSAE+7WQws0Sayczwz8FQ==", rreqTo = "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="});
Response: ApiReceiveR (ReceiveResponse {rresPayload = "\t^\167\179\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\202\132\&5i\227BqD\206\173^MY\153\163\208\204\249+\142\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULd”})
```

So far, so good.

Although the transaction is present in _tm1_, it’s not actually possible to access it due to the _sender cannot be a recipient check_. But that isn’t an issue normally, as the state of our transaction is stored in geth1’s private chain. Hence if _tm1_ dies, it has the private chain available locally.

However, if we delete geth1’s private state DB it’s not possible to recover this private state. The reason being that when the node resyncs when it receives a private transaction, it requests that transaction from _tm1_. However, the _sender cannot be a recipient check_ kicks in which prevents _geth1_ from being able to recover the private transactions from _tm1_. This results in the following error:

```
2017 Aug-07 15:50:52847745 [WARN] Error performing API request: ApiReceive (Receive {rreqKey = "mcQktPbaCa+xFUPMP0rGRzROmP/4zWxfpUWkXeET0Tj/b9D5wuqTmYXQIj/KYFdgsZSAE+7WQws0Sayczwz8FQ==", rreqTo = "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="}); encrypt: Sender cannot be a recipient
CallStack (from HasCallStack):
  error, called at ./Constellation/Enclave/Payload.hs:56:24 in constellation-0.1.0.0-6e8lqFuBPtzCz3iEft1Zk0:Constellation.Enclave.Payload
```

This node can no longer transact with this contract which it earlier created.

The same problem manifests itself for backup instances too.

**Comment by tylobban** [comment]
There are a number of use cases emerging where you do want to make data private just for yourself. This would necessitate being able to send private transactions to yourself and no one else. Given that, and the above, this check may need to fall away. Cc @patrickmn

**Comment by conor10** [comment]
It would be great to have that flexibility. That being said, I'm sure there's a good reason why it was designed this way.

**Comment by patrickmn** [comment]
There's two parts to this, the first being what sounds like a bug. "Sender cannot be a recipient" should not happen when retrieving old payloads.

The second is a feature request which should be logged separately. The simple reason why you cannot currently send just to yourself is that all payloads are encrypted with NaCl box, and that requires both a sender and a receiver who cannot be the same. (That restriction is a property of the EC key agreement in NaCl; we simply sanity check it.)

**Comment by patrickmn** [comment]
Feature request: https://github.com/jpmorganchase/constellation/issues/48
