### ISSUE TITLE
Any ETA on when documentation would be published?

### ISSUE THREAD

**Issue by ashfaq-shaik** [jpmorganchase/constellation#55]
For the benefit of us non-haskell programmers, it would be helpful if some consistent documentation could be published. 

We had run into some trouble with configuration related issues in a non vagrant/example environment

**Comment by patrickmn** [comment]
WIP here: https://github.com/jpmorganchase/constellation/blob/new-readme/README.md

ETA is hopefully soon -- but happy to accept a PR or tailor to whatever problems you were experiencing.

**Comment by ashfaq-shaik** [comment]
Thanks Patrick. Much appreciated

**Comment by lucasvo** [comment]
@patrickmn Thanks for a link to that branch. The documentation is definitely a big improvement over today's README and I think it would be even more helpful for others if it was merged into master ;)

**Comment by cartazio** [comment]
the revised readme seems to have been up for a while, closing
