### ISSUE TITLE
What kind of metadata is collectible?

### ISSUE THREAD

**Issue by miohtama** [jpmorganchase/constellation#6]
It is not an obvious from README, so I post a question here.

How much communication metadata Constellation exposes? For example, is it possible for others to know the payload sender and receiver?

**Comment by patrickmn** [comment]
Currently:
  - The nodes all share information about which public keys are owned by which node endpoints as part of a regular synchronization. (Currently we depend on users self-managing TLS termination to get transport security, but plan to make inter-node traffic HTTP2, and thus TLS, only.)
  - A Constellation client (see https://github.com/jpmorganchase/quorum/tree/master/private) communicates the sender public key (not private key -- that is in the "Enclave,") payload plaintext, and recipient public keys, over a UNIX domain socket when they want to send something to somebody else
  - The actual contents of an encrypted payload being transmitted over the network to another node is https://github.com/jpmorganchase/constellation/blob/master/Constellation/Enclave/Payload.hs#L13-L19 (the sender's public key, the MK-encrypted ciphertext, its nonce, the recipient-public-key-encrypted box containing the MK for the current recipient--each recipient node gets only their own box--and the nonce for the boxes.) Note that the public keys of the recipients aren't included, the recipient nodes will simply try to decrypt their box which might fail.

Hope this provides a little detail. We will add this and more to the docs soon.
