### ISSUE TITLE
Version number incorrect in Release 0.2.0

### ISSUE THREAD

**Issue by mattcrooks** [jpmorganchase/constellation#63]
Small issue, it looks like the version number has not been updated in 0.2.0

https://github.com/jpmorganchase/constellation/blob/14997fbb8d5ae0b2db6ea182fcabad5d69ed7b23/Constellation/Node/Main.hs#L46

However, it has been bumped to 0.3.0 on master

**Comment by cartazio** [comment]
thanks for pointing this out, 
subsequent releases will do a better job :)
