### ISSUE TITLE
Too many open files -- Unix IPC

### ISSUE THREAD

**Issue by mkqaimari** [jpmorganchase/constellation#64]
Hello!

I'm working on JPMorgan's Quorum where I wrote a simplistic private smart contract and I'm hitting it with as much as possible of transactions to stress test it. The configuration I'm using is the 7nodes example. (https://github.com/jpmorganchase/quorum-examples)

 I ended-up with 200 Tx/sec. When I checked the logs I found that constellation-node is logging "Too Many Open Files" while trying to connect to other constellation nodes using Unix IPC. I raised the soft and the hard limits of file descriptor to 1 million with no use as it seems that constellation-node is not honoring the limit. By listing the file descriptors under /proc/<PID>/fd I'm always getting less than 1024 files. I'm not sure what I'm doing wrong here and I hope that someone can help.

Cheers!

**Comment by mkqaimari** [comment]
This issued should be closed and opened at the Quorum repository.

 More details about this issue are at: https://stackoverflow.com/questions/47887465/quorum-constellation-too-many-open-files

**Comment by cartazio** [comment]
@jpmsam  this is a bug on the quorum side aroudn http header settings if the associated SO post comments are correct, closing this for constellation for now.
