### ISSUE TITLE
The source code does not work right for "--permissioned" flag in 2.0.0 release

### ISSUE THREAD

**Issue by Lispre** [jpmorganchase/constellation#65]
The 2.0.0 source code does not deliver "datadir" parameter to the permissions.go's function.
Then, geth cannot get the permissioned-nodes.json file's path even through file has been prepared there.

**Comment by chiruei56** [comment]
I found that when --permission flag is added, permissioned-nodes.json should be placed in the **directory** where `start.sh` is placed.

**Comment by patrickmn** [comment]
This should be fixed in the latest Quorum `master`
