### ISSUE TITLE
--workdir doesnt exist anymore

### ISSUE THREAD

**Issue by MitchK** [jpmorganchase/constellation#66]
Hi,

According to https://github.com/jpmorganchase/constellation/blob/master/sample.conf#L23 I was trying to generate a key pair using 
```
constellation-node --workdir data --generatekeys=node
```

However, that option does not exist (anymore):
```
constellation-node: user error (unrecognized option `--workdir'
```

I'm using constellation 0.2.0

**Comment by patrickmn** [comment]
The `workdir` option was only recently added (it's in master, but not 0.2.0) -- it should work without that option specified
