### ISSUE TITLE
About IPC between quorum node and constellation node in two independent dockers

### ISSUE THREAD

**Issue by wangjohnny** [jpmorganchase/constellation#68]
I installed quorum node and constellation node in two independent dockers. How can I to config to make both them comunicate using IPC?

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/252#issuecomment-361707485

**Comment by vietlq** [comment]
@wangjohnny you can check https://github.com/jpmorganchase/quorum-examples which shows how to allow Constellation/Tessera node to communicate with Geth node in different Docker containers via Unix domain socket created by Constellation/Tessera. In short they must share the same Docker volume.
