### ISSUE TITLE
How To compile and install from source on CentOS 7

### ISSUE THREAD

**Issue by jotorren** [jpmorganchase/constellation#69]
Everybody who plans to build Constellation binaries from source on CentOS, must install supporting libraries:

- **libdb-devel**, **leveldb-devel**, **libsodium-devel**, **zlib-devel**,  **ncurses-devel**

but also:

- **glibc-static**, **libstdc++-static** (otherwise you will see a "_Missing C library: stdc++_" error, when compiling "double-conversion")
- **gcc-c++** (in order to avoid the "_gcc error trying to exec 'cc1plus' execvp no such file or directory_" error)

**Comment by cartazio** [comment]
this should be searchable for those who need it, thanks for posting. Since various linux distro's have different packaging regimes etc, i'm going to close this for now. But this is useful info to have shared. Thanks!
