### ISSUE TITLE
Constellation stops working if transaction executed with self key 

### ISSUE THREAD

**Issue by bansatya** [jpmorganchase/constellation#70]
If a private transaction is executed with self public key of the node, then constellation stops working.

Step 1 : Get a docker container of Ubuntu with latest version of Quorum and constellation. 

Step 2: Get the 7 nodes example from GitHub. Start the nodes with raft script. 

Step 3: Considered 1st and 2nd node for the test. Execute private contract from 1st node with correct public key of 2nd node. Transactions is executed successfully and contract mined. 

Step 4: Executed the contract with self public key of 1st node. Transaction fails. 

3.Repeat step 3, it fails every time until constellation of node 1 restarted again. 

I am not sure why constellation stops working after step 4 execution. I remember, earlier version was not having this issue.

**Comment by patrickmn** [comment]
I think this is the same issue as https://github.com/jpmorganchase/constellation/issues/47

**Comment by patrickmn** [comment]
Copying my comment from https://github.com/jpmorganchase/quorum/issues/253#issuecomment-362651082:

Please try specifying `privateFor=[]` to mark the transaction as private and visible only to yourself. Putting your own public key isn't necessary, although it shouldn't be causing this kind of error condition.

**Comment by bansatya** [comment]
Executed same set of steps in 7 nodes with Quorum 2.0.1 and constellation 0.3.0. 
I am getting same issue - constellation stops working.

**Comment by patrickmn** [comment]
Please try again with Quorum 2.0.1 (not the pre-release) and Constellation 0.3.2. A similar issue was accidentally introduced in the switch to the non-JSON send/receive APIs.
