### ISSUE TITLE
Stack build not working on OSX if not using homebrew; docs need updated

### ISSUE THREAD

**Issue by jrgleason** [jpmorganchase/constellation#71]
For many reasons I choose not to use homebrew, so I installed BerkleyDB manually. Because of this the stack cmd is `stack install --extra-include-dirs=/usr/local/BerkleyDB.5.3/include --extra-lib-dirs=/usr/local/BerkleyDB.5.3/lib` I believe this should be noted in the README or BUILD file. I am more than happy to put together a pr when I can.

**Comment by cartazio** [comment]
we'll be dropping support for BDB shortly, since its been a huge pain, closing htis for now since thats gonna be addressed soon :)
