### ISSUE TITLE
Constellation peer discovery questions

### ISSUE THREAD

**Issue by MitchK** [jpmorganchase/constellation#77]
I'm bringing back the question about how constellation peers discover and connect to each other during runtime since we (eventually) want to run Quorum in production, automating the provisioning of private Quorum networks. Every network should allow new nodes to join. 

We basically want to achieve that a new node can join a network without having to tell other nodes to update a local configuration file (```tm.conf```, ```otherNodes = [...]```and restart them).

In Slack, @patrickmn mentioned that a Constellation node behaves like a Geth boot node (https://go-quorum.slack.com/archives/C68NY0QQZ/p1517276479000180?thread_ts=1517258552.000240&cid=C68NY0QQZ)

I have the following questions:

- Very basic question to confirm: Is it correct that if Constellation node A connects to node B, and C connects to B, in the end, A and C will be connected together as well?
- In an end-to-end setup (automating the provisioning of Quorum networks), would we then at minimum run a Geth boot node along with a Constellation "boot node"?
- Is there any form of documentation how Constellation's p2p discovery protocol works? (wish I had more time to learn haskell 😃 )

**Comment by cartazio** [comment]
theres currently no support for dynamic peer discovery in any robust or meaningful way, aside from at application start time.

**Comment by patrickmn** [comment]
Hi @MitchK,

> Very basic question to confirm: Is it correct that if Constellation node A connects to node B, and C connects to B, in the end, A and C will be connected together as well?

That's right. Every Constellation node identifies itself to other nodes with the FQDN given in the `url` field, and every Constellation node propagates information about the peers (and their `url`) that it has seen to other nodes. In the end, every node has a consistent view of the entire network, even if `othernodes` was initially only a few nodes, or only one node, or even nothing (i.e some node connected to this one -- which is how the first node in the 7nodes example learns about the others.)

> In an end-to-end setup (automating the provisioning of Quorum networks), would we then at minimum run a Geth boot node along with a Constellation "boot node"?

You don't really need a "bootnode", per se, if you can reliably identify/discover other Constellation nodes that new ones can connect to. If it's easier to just have one Constellation node that everyone connects to that is the "bootnode", that works too. The nodes will connect to it, learn about all of the other nodes, and then connect to them (and no longer rely on the bootnode for the lifetime of the process.)

> Is there any form of documentation how Constellation's p2p discovery protocol works? (wish I had more time to learn haskell 😃 )

It's basically this:

  - When connecting to another node (i.e. from `othernodes`, or a node we've learned about), tell it about all the nodes we know about it
  - When a node connects to us, it sends a list of all its known peers, thus it's perfectly fine to start nodes with `othernodes = []` if you know another one will connect to it
  - On startup, immediately synchronize with the nodes in `othernodes`
  - Roughly every 5 minutes after that, synchronize with every node we've learned about (usually the whole network)

Hope that helps.

**Comment by fabianoa** [comment]
Hi guys,

I'm having a little problem with the constellation sync process. Old/wrongs urls are propagated and I can't delete them. I'm hoping that the protocol will remove them automatically because the process of sync fails several times, but it doesn't.

[WARN] Synchronization failed: InvalidUrlException "http://10.107.7.118:9000partyinfo" "Invalid URL"

My question is where the URLs list is stored and how to remove it?

**Comment by fixanoid** [comment]
@fabianoa opened a new issue to track this, thanks!
