### ISSUE TITLE
Support for modifying configuration while running

### ISSUE THREAD

**Issue by jmcnevin** [jpmorganchase/constellation#78]
We currently start constellation using an IP whitelist given as a command line argument, but it would be nice to be able to update this IP whitelist while the application is running, perhaps by reloading the configuration file if it is modified.  Does this functionality currently exist?

**Comment by cartazio** [comment]
correct support for dynamic membership changes along with some related feature changes wont happen until the internals are swapped out for a replication algorithm such as RAFT or a total ordering PAXOS variant
