### ISSUE TITLE
Getting "certificate rejected: Certificate validation failed" Error in Constellation 0.3.2

### ISSUE THREAD

**Issue by Purbaja** [jpmorganchase/constellation#79]
While running more than one quorum node in a same server with public ip specified in the 'constellation-start.sh' script, we are getting "certificate rejected: Certificate validation failed" error whenever trying to start the second node.
We observed that, for the second node running in the same box the tls certificate related entries are not getting populated in the "tls-know-clients" or "tls-known-server" file under datadir folder.
Only one entry is present against the server ip in the "tls-know-clients" or "tls-known-server" files which is for the first quorum node -
{
    "hosts": {
        "X.X.X.142": [
            {
                "data": "F8:16:53:9A:88:BB:EC:68:7F:30:AB:70:E4:0B:F4:29:48:D8:0C:D3:E5:9C:99:C1:B3:D7:86:A7:1F:4B:89:32:F1:D5:BB:B0:88:E5:21:D5:35:FA:B3:8D:59:16:A6:77:8C:1D:60:35:EA:2D:25:B5:EF:B3:03:9C:ED:9E:CB:52",
                "type": "rsa-sha512"
            }
        ]
    }
}

Why the second node's tls certificate related entries are not getting populated during node startup?

**Comment by fixanoid** [comment]
@Purbaja this is a bug in TLS configuration in Constellation: it bind the keys per ip and not per ip:port config. This is fixed in [Tessera](https://github.com/jpmorganchase/tessera), so consider either disabling TLS in Constellation or moving to Tessera.
