### ISSUE TITLE
remove non-sqlite storage backends

### ISSUE THREAD

**Issue by cartazio** [jpmorganchase/constellation#80]
@jpmsam  : a number of the issues will be resolved if we drop all non sqlite backends, because that backend is both easy to static link into the application on all platforms, and friendly to query outside of the application.

I think the right  near term fix is to do that internal change, but still accept the backend flag but emit a warning when any  non sqlite backend is selected, and then also add a mutually exclussive CLI flag for setting the directory of the storage file. (this is so that current scripts wont totallly break as things get migrated to the new version)

**Comment by cartazio** [comment]
(a number of current tickets are around this and all spread out, but creating a new one to keep discussion simple for now
)

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/constellation/issues/37

I think a rough consensus is that supporting `dir` and `sqlite` with `sqlite` being the default would be good. (Note though that SQLite is also the worst performing of all the options.)

You could use CPP and leave the other backends disabled (but not removed) by default.

**Comment by cartazio** [comment]
nope, they're dead,
https://github.com/jpmorganchase/constellation/pull/82 fixes it all
