### ISSUE TITLE
Package for ARM

### ISSUE THREAD

**Issue by malek87** [jpmorganchase/constellation#81]
Can someone provide a constellation package for Rpi / ARM? Unfortunately I can not install GHC due to eroor "couldn't figure out LLVM version! Make sure you have installed LLVM 3.9". .. LLVM 3.9 is installed ...

**Comment by cartazio** [comment]
use a prepackaged GHC for ARM from Debian or Fedora? we dont support ARM platforms at the moment, and are unlikely to have a decent build env for ARM for the forseeable future on this project
