### ISSUE TITLE
Delete entry from database

### ISSUE THREAD

**Issue by nottherealbatman** [jpmorganchase/constellation#83]
I found this pullrequest https://github.com/jpmorganchase/constellation/pull/26 on deleting entries from the database but I can't fully figure out how to actually call the private api to do so. My haskell knowledge is pretty much non-existent so any pointers would be great.

I'm running constellation with quorum in a docker container

**Comment by fixanoid** [comment]
Hi, delete api has been implemented with this pull but not the delete Quorum implementation. This is going to be done in future versions.
