### ISSUE TITLE
Error while replicating the 7nodes example

### ISSUE THREAD

**Issue by vmadan2** [jpmorganchase/constellation#85]
Hi there,

I'm getting the following error while using the given scripts to setup quorum. I need some help in understanding what I might be doing wrong. 

Error:
`2018 May-03 00:55:50311235 [WARN] Error performing API request: ApiSend (Send {sreqPayload = "`\128`@R4\128\NAKa\NUL\DLEW`\NUL\128\253[P`@Q` \128a\SOHa\131\&9\129\SOH\128`@R\129\SOH\144\128\128Q\144` \SOH\144\146\145\144PPP\128`\NUL\129\144UPPa\SOH\ETB\128a\NULJ`\NUL9`\NUL\243\NUL`\128`@R`\EOT6\DLE`SW`\NUL5|\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\144\EOTc\255\255\255\255\SYN\128c*\SUB\252\217\DC4`XW\128c`\254G\177\DC4`\128W\128cmL\230<\DC4`\170W[`\NUL\128\253[4\128\NAK`cW`\NUL\128\253[P`j`\210V[`@Q\128\130\129R` \SOH\145PP`@Q\128\145\ETX\144\243[4\128\NAK`\139W`\NUL\128\253[P`\168`\EOT\128\&6\ETX\129\SOH\144\128\128\&5\144` \SOH\144\146\145\144PPP`\216V[\NUL[4\128\NAK`\181W`\NUL\128\253[P`\188`\226V[`@Q\128\130\129R` \SOH\145PP`@Q\128\145\ETX\144\243[`\NULT\129V[\128`\NUL\129\144UPPV[`\NUL\128T\144P\144V\NUL\161ebzzr0X P2\152\129^\199[k\155_L\216,AF\148\252\210\DLE\128\US\182\203\226\206_\147Vf\149\177\141\NUL)\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL*", sreqFrom = "FKmIBrkWF0nES93QruM5QTIvMDAyU/9YU8D5Om3w8lA=", sreqTo = ["VI8j0Loeeu18J2TF1JSgba8D+g/sqvAK5PyR0OdHJBE="]}); sendRequest: Errors while running sendPayload: [Left "Unknown recipient\nCallStack (from HasCallStack):\n  error, called at ./Constellation/Node.hs:164:21 in constellation-0.1.0.0-bO6yomQcNv4mJID9Sq40H:Constellation.Node"]
`
The configuration I've built is as follows:
 Script 1:
`#!/bin/bash
set -eu -o pipefail

echo "[*] Removing any existing Geth/Bootnode/Golang/Constellation/Porosity/Quorum folders [*]"
rm -rf /usr/local/bin/geth
rm -rf /usr/local/bin/bootnode
rm -rf /usr/local/go
rm -rf /usr/local/bin/constellation-node
rm -rf /usr/local/bin/porosity
rm -rf quorum
rm -rf constellation*
rm -rf golang*

#1. Install build deps
echo "[*] Installing build dependencies [*]"
echo  | add-apt-repository ppa:ethereum/ethereum
apt-get update
apt-get install -y build-essential unzip libdb-dev libleveldb-dev libsodium-dev zlib1g-dev libtinfo-dev solc sysvbanner wrk

#2. Download & Install Constellation
echo "[*] Downloading and Installing Constellation [*]"
CVER="0.2.0"
CREL="constellation-$CVER-ubuntu1604"
wget -q https://github.com/jpmorganchase/constellation/releases/download/v$CVER/$CREL.tar.xz
tar xfJ $CREL.tar.xz
cp $CREL/constellation-node /usr/local/bin && chmod 0755 /usr/local/bin/constellation-node
rm -rf $CREL*

#3. Download & Install Golang
echo "[*] Downloading and Installing Golang [*]"
GOREL=go1.9.3.linux-amd64.tar.gz
wget -q https://dl.google.com/go/$GOREL
tar xfz $GOREL
mv go /usr/local/go
rm -f $GOREL
PATH=$PATH:/usr/local/go/bin
echo 'PATH=$PATH:/usr/local/go/bin' >> /home/dranz3r/.bashrc
rm -rf $GOREL

#4. Download & Install Quorum
echo "[*] Downloading and Installing Quorum [*]"
git clone https://github.com/jpmorganchase/quorum.git
pushd quorum >/dev/null
git checkout tags/v2.0.0
make all
cp build/bin/geth /usr/local/bin
cp build/bin/bootnode /usr/local/bin
popd >/dev/null

#5. Download & Install Porosity
echo "[*] Downloading and Installing Porosity [*]"
wget -q https://github.com/jpmorganchase/quorum/releases/download/v1.2.0/porosity
mv porosity /usr/local/bin && chmod 0755 /usr/local/bin/porosity

#6. Clean up raft$i and Qdata directories
echo "[*] Removing any existing Raft/Qdata folders and passwords[*]"
rm -rf raft*
rm -rf qdata
rm -rf password*

#7. Create qdata/logs directory
echo "[*] Creating logs folder in Qdata [*]"
mkdir -p qdata/logs

#8. For each node:
for i in {1..7}
do
	#9a. Create 7 password files, genesis.json file
	echo "$i. [*] Creating new password [*]"
	echo password$i > password-file-$i.txt
	#9b. Create raft$i, qdata/node$i/keystore, qdata/node$i/geth, qdata/c$i directories.
	echo "$i. [*] Creating raft, node/keystore, node/geth, qdata/constellation directories [*]"
	mkdir -p raft$i qdata/node$i/{keystore,geth} qdata/c$i/keystore
	#9c. Create geth node config in qdata/node$i/geth.
	echo "$i. [*] Creating Geth Config and Logging in raft$i directory's Setup.log file [*]"
	nohup geth --datadir raft$i 2>> raft$i/setup.log &
	#9d. Add data to raft$i/static-nodes.json.
	echo "$i. [*] Adding data to Raft -> static-nodes.json file. Update this file with ./2-node-copy.sh before running Constellation & Geth  [*]"
	sleep 3
	echo "[\"$(cat raft$i/setup.log | grep -oEim 1 '(enode.*@)')127.0.0.1:2100$i?discport=0&raftport=2300$i\"]" >> raft$i/static-nodes.json 
	#9e. Create a new Ethereum account with passwords as password-file$i.txt.
	echo "$i. [*] Creating default ethereum account for Node $i[*]"
	geth --datadir raft$i --password password-file-$i.txt account new
	#9f. Stop all geth actions. 
	echo "$i. [*] Stopping geth [*]"
	killall geth
	#9g. Generate Constellation Keys (--generatekeys = constellation_node_$i) for each in qdata/c$i/keystore. 
	echo "$i. [*] Generating Constellation Keys for Node $i [*]"	
	cd raft$i
	constellation-node --generatekeys=constellation_node_$i
	cd ..
	sleep 3	
#close loop for Step #8
done

killall constellation-node`

Script 2:
`#!/bin/bash
set -eu -o pipefail

for i in {1..7}
do 
	if [ $i -eq 1 ]  
	then
		echo "[\"$(cat raft$i/static-nodes.json | grep -oEim 1 '(enode.*@)')127.0.0.1:2100$i?discport=0&raftport=2300$i\"," > raft1/static-nodes.json
	elif [[ $i -gt 1 ]] &&  [[ $i -lt 7 ]] 
	then
		echo "\"$(cat raft$i/static-nodes.json | grep -oEim 1 '(enode.*@)')127.0.0.1:2100$i?discport=0&raftport=2300$i\"," >> raft1/static-nodes.json
	else
		echo "\"$(cat raft$i/static-nodes.json | grep -oEim 1 '(enode.*@)')127.0.0.1:2100$i?discport=0&raftport=2300$i\"]" >> raft1/static-nodes.json
	fi
done

sudo cp raft1/static-nodes.json raft2/static-nodes.json
sudo cp raft1/static-nodes.json raft3/static-nodes.json
sudo cp raft1/static-nodes.json raft4/static-nodes.json
sudo cp raft1/static-nodes.json raft5/static-nodes.json
sudo cp raft1/static-nodes.json raft6/static-nodes.json
sudo cp raft1/static-nodes.json raft7/static-nodes.json
`

Script 3: 
`#!/bin/bash
set -eu -o pipefail

#1-#9 are in new-steps1.sh file

#10. Before continuing, edit static-nodes.json file to add all nodes in the same order

#11. Start stuff: for each node, do: 
for i in {1..7}
do
	#11a. Copy raft$i/keystore/$(sudo ls raft$i/keystore) to qdata/node$i/keystore/acckey
	echo "$i. [*] Copying Ethereum Account Key from Raft to Qdata folder [*]"	
	sudo cp raft$i/keystore/$(sudo ls raft$i/keystore) qdata/node$i/keystore/acckey
	#11b. Copy raft$i/geth/nodekey to qdata/node$i/geth/nodekey
	echo "$i. [*] Copying Nodekey from Raft to Qdata [*]"
	cp raft$i/geth/nodekey qdata/node$i/nodekey	
	#11c. Copy raft$i/constellation.pub and constellation.key to qdata/c$i/keystore/
	echo "$i. [*] Copying Constellation Keys from Raft to Qdata [*]"
	cp raft$i/constellation_node_$i* qdata/c$i/keystore/	
	#11d. Copy raft$i/static-nodes.json to qdata/node$i/static-nodes.json
	echo "$i. [*] Copying Static Nodes from Raft to Qdata as Static and Permissioned Nodes [*]"
	sudo cp raft$i/static-nodes.json qdata/node$i/static-nodes.json
	sudo cp raft$i/static-nodes.json qdata/node$i/permissioned-nodes.json
	#11e. Initiate Geth
	echo "$i. [*] Initiate Geth [*]"
	geth --datadir qdata/node$i init genesis.json &	
#close loop for Step #11
done 

for i in {1..7}
do
	#11f. Initiate Constellation with conf command "constellation-node --url=https://127.0.0.$i:900$i/ --port=900$i --workdir=$DDIR --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key 
	#	--othernodes=https://127.0.0.1:9001/".
	# --url=https://127.0.0.1:900$i/ --port=900$i --socket=$DDIR/tm.ipc --publickeys=$DDIR/keystore/constellation_node_$i.pub --privatekeys=$DDIR/keystore/constellation_node_$i.key --othernodes=https://127.0.0.1:900$i/
	#echo "$i [*] Initiating Constellation with Node $i Config [*]" 	
	DDIR="qdata/c$i"
	CMD="nohup constellation-node tm$i.conf"  #2>> qdata/logs/constellation.log &
	echo "$CMD >> qdata/logs/constellation$i.log 2>&1 &"
	$CMD 2>> qdata/logs/constellation$i.log & #>> "qdata/logs/constellation$i.log" 2>&1 &
done

DOWN=true
while $DOWN; do
    sleep 0.1
    DOWN=false
    for i in {1..7}
    do
	if [ ! -S "qdata/c$i/tm.ipc" ]; then
            DOWN=true
	fi
    done
done

for i in {1..7}
do
	#11g. Initiate geth for each node with "geth --datadir qdata/node$i init genesis.json"
	echo "$i [*] Initiating Geth with Node $i Config [*]" 
	ARGS="--nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints"
	PRIVATE_CONFIG=tm$i.conf nohup geth --datadir qdata/node$i $ARGS --raftport 2300$i --rpcport 2200$i --port 2100$i --unlock 0 --password password-file-$i.txt 2>>qdata/logs/geth$i.log &

#close loop for Step #11f
done
`

tm$i.conf

`url = "https://127.0.0.1:9001/"
port = 9001
socket = "qdata/c1/tm.ipc"
othernodes = ["https://127.0.0.1:9001/"]
publickeys = ["qdata/c1/keystore/constellation_node_1.pub"]
privatekeys = ["qdata/c1/keystore/constellation_node_1.key"]
storage = "qdata/c1/constellation"
verbosity = 3`

**Comment by fixanoid** [comment]
Hi, looks like the version of Constellation needed for 2.0.0 is wrong. Please build from master

**Comment by horca17** [comment]
on the first node, or the main node, config tm1.conf using only othernodes = [] and all other rnodes = ["https://127.0.0.1:9001/"], so constellation will work without errors.
