### ISSUE TITLE
constellation-node: storage: createDirectory: permission denied (Permission denied)

### ISSUE THREAD

**Issue by omkarkhair** [jpmorganchase/constellation#86]
I'm trying to run 7nodes examples on CentOS 7. I have built and installed `constellation-node` using haskell stack.

I tried running a single constellation node through command line and hit this error.
```
[centos@ip-172-31-40-40 7nodes]$ constellation-node --url=https://127.0.0.1:9001/ --port=9001 --workdir=qdata/c1 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/

10:33:29 [INFO] Log level is LevelWarn
Unlocking tm.key
Unlocked tm.key
10:33:29 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
constellation-node: storage: createDirectory: permission denied (Permission denied)

```
Am I missing something? Will I have to install constellation-node as root and do a `sudo` run?

**Comment by omkarkhair** [comment]
`sudo chmod 777 .` on the 7nodes directory solved this for me. But is this an ideal way to do it?

**Comment by fixanoid** [comment]
@omkarkhair constellation requires directory level user permissions because it creates a bunch of configs and database storage files where it runs. Permissions are required to run it.
