### ISSUE TITLE
ProxyConnectException

### ISSUE THREAD

**Issue by swettdj** [jpmorganchase/constellation#89]
Hello, I'm trying to run two different quorum node with two different constellation node.
First node and constellation node run perfectly, but when I try to boot up the second constellation node that point to the first one through `othernodes` parameter, in log file I get the following error:

> (ProxyConnectException "0.0.0.0" 9001 (Status {statusCode = 403, statusMessage = "Tunnel or SSL Forbidden"}))

Both nodes are on the same machine and I tried both to point to 127.0.0.1 and to 0.0.0.0 but the result is the same.

The tm.conf file is:
`url = "http://127.0.0.1:9002/"
port = 9002
socket = "qdata/constellation2/tm.ipc"
othernodes = ["http://0.0.0.0:9001/"]
publickeys = ["node2/constellation-node2.pub"]
privatekeys = ["node2/constellation-node2.key"]
passwords="passwords.txt"
storage = "qdata/constellation2"
verbosity = 3
ipwhitelist=["127.0.0.1","::1"]
tls = "off"
tlsservertrust="insecure-no-validation"
tlsclienttrust="insecure-no-validation"`

Could some one help me?
Thanks

**Comment by fixanoid** [comment]
Address of the other node seems to be wrong. Please try with 127.0.0.1
