### ISSUE TITLE
Send password as argument

### ISSUE THREAD

**Issue by AugustoL** [jpmorganchase/constellation#9]
Is there a way to start sending password as argument? it would be very helpful, we are working setting up +3 constellation nodes with quorum and this will make start-up scripts easier for us.

**Comment by patrickmn** [comment]
Agree that you should be able to specify e.g. a passwords file (or the password directly) with `--password`.

Right now, you can actually do this with either `echo "mysecretpassword" | constellation-node example.conf` or creating a file `passwords` and then running `constellation-node example.conf < passwords`

**Comment by AugustoL** [comment]
Thanks @patrickmn , solved using `echo "mysecretpassword" | constellation-node example.conf`

**Comment by hermanjunge** [comment]
:+1: For a command line option with a file.

**Comment by patrickmn** [comment]
In progress: https://github.com/jpmorganchase/constellation/pull/19
