### ISSUE TITLE
No API documention

### ISSUE THREAD

**Issue by a651694192** [jpmorganchase/constellation#94]
I find there is not any documentation about API spec, can you add that?

**Comment by fixanoid** [comment]
Hi, this is something we will be working on and will publicize once available. The API as implemented could be seen in this repo for fully supported methods and here: https://github.com/jpmorganchase/quorum/tree/master/private/constellation for Quorum side of the API.

**Comment by a651694192** [comment]
Ummmm.... I need to get all the Constellation public keys to easy sending private transactions, this may need to be accomplished by  constellation API.

**Comment by fixanoid** [comment]
Hi, the API is detailed in the new Tessera docs here: https://github.com/jpmorganchase/tessera/wiki/Interface-&-API-Details and swagger is here: https://jpmorganchase.github.io/tessera-swagger/index.html
