### ISSUE TITLE
Failed to run 7nodes at geth execution

### ISSUE THREAD

**Issue by aroommen** [jpmorganchase/constellation#95]
I am running the 7nodes examples with the vagrant setup and the run is stopping with the ./raft-init.sh execution itself. The run terminates with the following message

$ ./raft-init.sh
[*] Cleaning up temporary data directories
[*] Configuring node 1 (permissioned)
INFO [06-15|07:14:43] Allocated cache and file handles         database=/vagrant/examples/7nodes/qdata/dd1/geth/chaindata cache=16 handles=16
**Fatal: Failed to open database: sync /vagrant/examples/7nodes/qdata/dd1/geth/chaindata: invalid argument**

Steps involved
% git clone https://github.com/jpmorganchase/quorum-examples
% cd quorum-examples
% vagrant up
% vagrant ssh

And once inside the machine
% cd /vagrant/examples/7nodes/
% raft-init.sh
**Quits with the message that I had quoted above**

_I also found a lock in the data directory
$ ls qdata/dd1/geth/chaindata/
CURRENT  LOCK     LOG_      

I had made some progress by moving the qdata ( data directory ) from the vagrant shared directory to the VM home directory (/home/vagrant/qdata) but even with that I eventually ran into an IPC socket file issue. So I stopped with that direction as well.

**Comment by fixanoid** [comment]
Hi @aroommen the 7 nodes example is designed to run in a vagrant vm. Please install vagrant and follow the instructions written in this readme: https://github.com/jpmorganchase/quorum-examples

**Comment by aroommen** [comment]
@fixanoid Thanks for looking into this issue and for your suggestion. 
My issue has been observed after following the instructions in the readme. It's occurring inside the specified vagrant vm as you can see from the command workflow that I have listed in the original post.
