### ISSUE TITLE
How to run constellation nodes in one vm?

### ISSUE THREAD

**Issue by cosimoth** [jpmorganchase/constellation#97]
Hi all,
When setting up the 7-node example of Quorum, I wanna establish a private network to allow other node to join in. So I use private IP of virtual network to start the nodes instead of 127.0.0.1, ... , 127.0.0.7. 
However, there'll be Handshake errors when all nodes use one IP (even though ports are different). I wonder if is there any other way to make this? 
Thanks a lot.

**Comment by fixanoid** [comment]
@cosimoth this set up should work just fine, please check your routing and connectivity.

**Comment by cosimoth** [comment]
Thanks a lot for your reply.
However, when I change the IP configuration of constellation nodes in script `constellation-start.sh`
from
`CMD="constellation-node --url=https://127.0.0.$i:900$i/ --port=900$i ... `
to
`CMD="constellation-node --url=https://127.0.0.1:900$i/ --port=900$i ... `
errors actually occur (even though all IPCs are generated and I can attach the console).

In `qdata/logs/constellation1.log`:
> HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))

and in `qdata/logs/constellation2.log`:
> [WARN] Synchronization failed: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 9001
  secure               = True
  requestHeaders       = []
  path                 = "/partyinfo"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.sendBuf: resource vanished (Broken pipe))

Is there any step I missed?

**Comment by fixanoid** [comment]
@cosimoth your own url should always be on the same server with the IP. the other urls may be remote.

**Comment by cosimoth** [comment]
Sorry, I didn't get that. In other words, if I wanna set up 7 nodes on one server, and I use one IP with different ports (such as 127.0.0.1:9001, 127.0.0.1:9002, ...  127.0.0.1:9007 for each node) as constellation configuration, will anything go wrong?

**Comment by cosimoth** [comment]
Hi, @fixanoid 

In the 7-nodes example, I start Constellation nodes as
> constellation-node --url=https://127.0.0.1:9001/ --port=9001 --workdir=qdata/c1 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9002/ --port=9002 --workdir=qdata/c2 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9003/ --port=9003 --workdir=qdata/c3 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9004/ --port=9004 --workdir=qdata/c4 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9005/ --port=9005 --workdir=qdata/c5 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9006/ --port=9006 --workdir=qdata/c6 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/
constellation-node --url=https://127.0.0.1:9007/ --port=9007 --workdir=qdata/c7 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/

and Quorum nodes as (no change):
> geth --datadir qdata/dd1 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --permissioned --raftport 50401 --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt
geth --datadir qdata/dd2 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --permissioned --raftport 50402 --rpcport 22001 --port 21001 --unlock 0 --password passwords.txt
geth --datadir qdata/dd3 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --permissioned --raftport 50403 --rpcport 22002 --port 21002 --unlock 0 --password passwords.txt
geth --datadir qdata/dd4 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --permissioned --raftport 50404 --rpcport 22003 --port 21003 --unlock 0 --password passwords.txt
geth --datadir qdata/dd5 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --raftport 50405 --rpcport 22004 --port 21004 --unlock 0 --password passwords.txt
geth --datadir qdata/dd6 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --raftport 50406 --rpcport 22005 --port 21005 --unlock 0 --password passwords.txt
geth --datadir qdata/dd7 --nodiscover --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --raftport 50407 --rpcport 22006 --port 21006 --unlock 0 --password passwords.txt

there'll be errors when I deploy a private contract: 
> Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Wed, 01 Aug 2018 05:48:37 GMT] Server:[Warp/3.2.13]] Body:0xc420b0c780 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc43558cf00 TLS:<nil>}
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:3021:24
    at <anonymous>:1:14

However, a public contract is just fine. Could u pls help me to come through this? Thanks a lot.
