### ISSUE TITLE
constellation-node: command not found

### ISSUE THREAD

**Issue by manojvenkateswararaja** [jpmorganchase/constellation#98]
can anyone suggest me a solution.

**Comment by fixanoid** [comment]
@manojvenkateswararaja you need to build constellation to get the executables.  Please follow: https://github.com/jpmorganchase/constellation/blob/master/README.md#installation

**Comment by manojvenkateswararaja** [comment]
@fixanoid I did the installation that you have been mentioned in above comment but still iam getting constellation-node command not found and then iam running this setup in ubuntu which is running in virtual machine.

**Comment by manojvenkateswararaja** [comment]
Problem solved. Thank you @fixanoid
