### ISSUE TITLE
What is the purpose of a constellation node hosting more than one NaCl (Curve25519) public/private key pairs?

### ISSUE THREAD

**Issue by elizur-cartasense** [jpmorganchase/constellation#99]
Can Ethereum users from different Ethereum accounts using the same quorum node specify different constellation key public address as the privyFor parameter?

**Comment by fixanoid** [comment]
Hi @elizur-cartasense, multiple keys are used in a single node where each key is assigned to a participant and each key is used for a specific use. This feature never made it into Constellation, but in our next release of [Tessera](https://github.com/jpmorganchase/tessera) we will support multiple key pairs for each node

**Comment by lucykur** [comment]
Hi @fixanoid, Has this been added to the Tessera 0.8 release ?

**Comment by fixanoid** [comment]
@lucykur this feature has been added into Tessera v0.7+ please see https://github.com/jpmorganchase/tessera/wiki/Keys#multiple-keys
